[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/*"
  to = "/programming-list-page.html"
  status = 200

    [[redirects]]
  from = "/*"
  to = "/programming-details-page.html"
  status = 200